# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-29 08:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import otree.db.models
import otree_save_the_change.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('treatment', otree.db.models.IntegerField(null=True)),
                ('sent_amount', otree.db.models.IntegerField(choices=[[0, 'Option L'], [1, 'Option R']], null=True)),
                ('sent_back_amount_1', otree.db.models.IntegerField(choices=[[0, 'Option L'], [1, 'Option R']], null=True)),
                ('sent_back_amount_2', otree.db.models.IntegerField(choices=[[0, 'Option L'], [1, 'Option R']], null=True)),
                ('sent_back_amount_2_direct_hypo', otree.db.models.IntegerField(choices=[[0, 'Option L'], [1, 'Option R']], null=True)),
                ('sent_back_amount_2_if_A', otree.db.models.IntegerField(choices=[[0, 'Option L'], [1, 'Option R']], null=True)),
                ('sent_back_amount_2_if_B', otree.db.models.IntegerField(choices=[[0, 'Option L'], [1, 'Option R']], null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trust_simple_three_group', to='otree.Session')),
            ],
            options={
                'db_table': 'trust_simple_three_group',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_gbat_arrived', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('_gbat_grouped', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('CQ_maxA', otree.db.models.IntegerField(choices=[[6, '6 ECU'], [12, '12 ECU'], [10, '10 ECU'], [0, '0 ECU'], [14, '14 ECU']], null=True)),
                ('CQ_payoff', otree.db.models.IntegerField(choices=[[6, '6 ECU'], [12, '12 ECU'], [10, '10 ECU'], [0, '0 ECU'], [14, '14 ECU']], null=True)),
                ('CQ_sumtask', otree.db.models.IntegerField(null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trust_simple_three.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trust_simple_three_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trust_simple_three_player', to='otree.Session')),
            ],
            options={
                'db_table': 'trust_simple_three_player',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trust_simple_three_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'trust_simple_three_subsession',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.AddField(
            model_name='player',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trust_simple_three.Subsession'),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trust_simple_three.Subsession'),
        ),
    ]
