# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-14 12:57
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('trust_simple_three', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='prolific_id',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
    ]
